local component = require("component")
local gpu = component.gpu

gpu.set(19, 2, "╤═════╧════╤")
gpu.set(19, 3, "│  Execute │")
gpu.set(19, 4, "├╌╌╌╌╌╌╌╌╌╌┤")
gpu.set(19, 5, "│   Edit   │")
gpu.set(19, 6, "├──────────┤")
gpu.set(19, 7, "│   Copy   │")
gpu.set(19, 8, "├╌╌╌╌╌╌╌╌╌╌┤")
gpu.set(19, 9, "│  Rename  │")
gpu.set(19, 10, "├╌╌╌╌╌╌╌╌╌╌┤")
gpu.set(19, 11, "│  Delete  │")
gpu.set(19, 12, "├──────────┤")
gpu.set(19, 13, "│   Exit   │")
gpu.set(19, 14, "└─────┬────┘")